/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.service.measures.power;

import com.google.gson.annotations.SerializedName;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * PowerRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-20T11:54:34.525205900+01:00[Europe/Warsaw]")
public class PowerRequest {
  @SerializedName("from")
  private OffsetDateTime from = null;

  @SerializedName("to")
  private OffsetDateTime to = null;

  @SerializedName("roomNr")
  private Integer roomNr = null;

  public PowerRequest from(OffsetDateTime from) {
    this.from = from;
    return this;
  }

   /**
   * Get from
   * @return from
  **/
  public OffsetDateTime getFrom() {
    return from;
  }

  public void setFrom(OffsetDateTime from) {
    this.from = from;
  }

  public PowerRequest to(OffsetDateTime to) {
    this.to = to;
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  public OffsetDateTime getTo() {
    return to;
  }

  public void setTo(OffsetDateTime to) {
    this.to = to;
  }

  public PowerRequest roomNr(Integer roomNr) {
    this.roomNr = roomNr;
    return this;
  }

   /**
   * Get roomNr
   * @return roomNr
  **/
  public Integer getRoomNr() {
    return roomNr;
  }

  public void setRoomNr(Integer roomNr) {
    this.roomNr = roomNr;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PowerRequest powerRequest = (PowerRequest) o;
    return Objects.equals(this.from, powerRequest.from) &&
        Objects.equals(this.to, powerRequest.to) &&
        Objects.equals(this.roomNr, powerRequest.roomNr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(from, to, roomNr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PowerRequest {\n");

    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    roomNr: ").append(toIndentedString(roomNr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
