/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.service.measures.power;

import com.google.gson.annotations.SerializedName;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * PowerResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-20T11:54:34.525205900+01:00[Europe/Warsaw]")
public class PowerResponse {
  @SerializedName("dates")
  private List<OffsetDateTime> dates = null;

  @SerializedName("powers")
  private List<Double> powers = null;

  public PowerResponse dates(List<OffsetDateTime> dates) {
    this.dates = dates;
    return this;
  }

  public PowerResponse addDatesItem(OffsetDateTime datesItem) {
    if (this.dates == null) {
      this.dates = new ArrayList<>();
    }
    this.dates.add(datesItem);
    return this;
  }

   /**
   * Get dates
   * @return dates
  **/
  public List<OffsetDateTime> getDates() {
    return dates;
  }

  public void setDates(List<OffsetDateTime> dates) {
    this.dates = dates;
  }

  public PowerResponse powers(List<Double> powers) {
    this.powers = powers;
    return this;
  }

  public PowerResponse addPowersItem(Double powersItem) {
    if (this.powers == null) {
      this.powers = new ArrayList<>();
    }
    this.powers.add(powersItem);
    return this;
  }

   /**
   * Get powers
   * @return powers
  **/
  public List<Double> getPowers() {
    return powers;
  }

  public void setPowers(List<Double> powers) {
    this.powers = powers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PowerResponse powerResponse = (PowerResponse) o;
    return Objects.equals(this.dates, powerResponse.dates) &&
        Objects.equals(this.powers, powerResponse.powers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dates, powers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PowerResponse {\n");

    sb.append("    dates: ").append(toIndentedString(dates)).append("\n");
    sb.append("    powers: ").append(toIndentedString(powers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
