/*
 * Measures Service
 * Micro service to get temperature and power measures in building
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@measures.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.service.measures.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * MeasuresResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-17T10:43:35.462286600+01:00[Europe/Warsaw]")
public class MeasuresResponse {

  @JsonProperty("measuresId")
  private String measuresId = null;

  @JsonProperty("measures")
  private List<MeasuresResponseMeasures> measures = null;

  @JsonProperty("errorMessage")
  private String errorMessage = null;

  public MeasuresResponse measuresId(String measuresId) {
    this.measuresId = measuresId;
    return this;
  }

  /**
   * Get measuresId
   * @return measuresId
   **/
  public String getMeasuresId() {
    return measuresId;
  }

  public void setMeasuresId(String measuresId) {
    this.measuresId = measuresId;
  }

  public MeasuresResponse measures(List<MeasuresResponseMeasures> measures) {
    this.measures = measures;
    return this;
  }

  public MeasuresResponse addMeasuresItem(MeasuresResponseMeasures measuresItem) {
    if (this.measures == null) {
      this.measures = new ArrayList<>();
    }
    this.measures.add(measuresItem);
    return this;
  }

   /**
   * Get measures
   * @return measures
  **/
  public List<MeasuresResponseMeasures> getMeasures() {
    return measures;
  }

  public void setMeasures(List<MeasuresResponseMeasures> measures) {
    this.measures = measures;
  }

  public MeasuresResponse errorMessage(String errorMessage) {
    this.errorMessage= errorMessage;
    return this;
  }

  /**
   * Get errorMessage
   * @return errorMessage
   **/
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MeasuresResponse measuresResponse = (MeasuresResponse) o;
    return Objects.equals(this.measures, measuresResponse.measures) &&
            Objects.equals(this.measuresId, measuresResponse.measuresId) &&
            Objects.equals(this.errorMessage, measuresResponse.errorMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(measures, measuresId, errorMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MeasuresResponse {\n");
    sb.append("    measuresId: ").append(toIndentedString(measuresId)).append("\n");
    sb.append("    measures: ").append(toIndentedString(measures)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
